# Site settings
title: Max's Blog
header-img: img/post-bg-04.jpg
email: max.kriester+githubio@gmail.com
description: "Now launching!"
baseurl: ""
url: "https://mkster.github.io/"
twitter_username: 
github_username:  mkster
facebook_username:
donation_link: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Gemfile", "Gemfile.lock", "unused_pages"]
